"""Pricing engine: convert extracted scope items into a priced bid.

Math (per the project spec, calibrated against Reference's actual Park Avenue
Elementary School bid):

    qty_with_waste = qty * (1 + waste_rate[unit])
    unit_labor     = unit_cost.hours_per_unit * wage.total
    unit_material  = unit_cost.material_per_unit
    total_cost     = qty_with_waste * (unit_labor + unit_material)

Bid markups apply to the line-item subtotal independently and sum:

    overhead       = subtotal * 20.0%
    tax            = subtotal *  8.5%
    bid_bond       = subtotal *  1.5%
    contingencies  = subtotal *  5.0%
    total          = subtotal + overhead + tax + bid_bond + contingencies
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Iterable, Mapping

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ScopeItem:
    code: str
    quantity: float
    unit: str
    description: str = ""


@dataclass(frozen=True)
class UnitCost:
    code: str
    trade: str
    hours_per_unit: float
    material_per_unit: float
    description: str = ""


@dataclass
class PrevailingWage:
    trade: str
    base_rate: float
    supplements: float
    total: float = field(init=False)

    def __post_init__(self) -> None:
        self.total = self.base_rate + self.supplements


@dataclass(frozen=True)
class BidLineItem:
    scope_item: ScopeItem
    unit_labor: float
    unit_material: float
    total_cost: float


@dataclass(frozen=True)
class BidMarkup:
    overhead: float = 0.20
    tax: float = 0.085
    bid_bond: float = 0.015
    contingencies: float = 0.05


@dataclass(frozen=True)
class Bid:
    line_items: tuple[BidLineItem, ...]
    subtotal: float
    overhead: float
    tax: float
    bid_bond: float
    contingencies: float
    total: float


# ---------------------------------------------------------------------------
# Defaults — domain data from the project spec
# ---------------------------------------------------------------------------


WASTE_RATES: dict[str, float] = {
    "EA": 0.0,
    "LF": 0.10,
    "SF": 0.10,
    "LS": 0.0,
}


def normalize_unit(unit: str) -> str:
    """Canonicalize a unit string. EA / LF / SF / LS plus their aliases."""
    u = unit.strip().upper().replace(".", "")
    if u in ("LF", "FT", "LIN FT", "LINEAR FT"):
        return "LF"
    if u in ("SF", "SQ FT", "SQFT"):
        return "SF"
    if u in ("EA", "EACH"):
        return "EA"
    if u in ("LS", "LUMP SUM"):
        return "LS"
    return u

# Orange County, NY (Warwick) prevailing wages — base + supplements per spec.
DEFAULT_WAGES: dict[str, PrevailingWage] = {
    "bricklayer": PrevailingWage("bricklayer", 56.58, 51.44),
    "stone_mason": PrevailingWage("stone_mason", 56.58, 51.44),
    "mason_tender": PrevailingWage("mason_tender", 37.10, 40.47),
    "ironworker": PrevailingWage("ironworker", 52.00, 55.80),
    "carpenter": PrevailingWage("carpenter", 48.25, 44.19),
    "painter": PrevailingWage("painter", 42.85, 37.69),
}

# Generated by scripts/extract_unit_costs_from_reference.py from
# test_data/Park_Avenue_Elementary_School.xlsx. Trade is set to "bricklayer"
# uniformly so that hours_per_unit * bricklayer_wage (=$108.02) reproduces
# Reference's unit-labor dollars exactly — the trade dimension is collapsed onto
# a single reference rate. Description is the spreadsheet line text minus
# the "WSn:" / "Rn:" prefix.
DEFAULT_UNIT_COSTS: dict[tuple[str, str], UnitCost] = {
    ("R1", "EA"): UnitCost("R1", "bricklayer", 1.046442, 0.0, description="Remove Door"),
    ("R2", "EA"): UnitCost("R2", "bricklayer", 0.603034, 0.0, description="Remove Transoms, Hardware"),
    ("R3", "EA"): UnitCost("R3", "bricklayer", 0.283781, 0.0, description="Remove Sealant, Fasteners"),
    ("R4", "EA"): UnitCost("R4", "bricklayer", 1.046442, 0.0, description="Remove Wood/Hollow Metal Frame"),
    ("R5", "EA"): UnitCost("R5", "bricklayer", 0.861984, 0.0, description="Remove Hardware from Door"),
    ("WS1", "LF"): UnitCost("WS1", "bricklayer", 0.057579, 0.50, description="Clean Cast Stone Bands, Re-point and Cover all Horizontal & Vertical Joints"),
    ("WS2", "LF"): UnitCost("WS2", "bricklayer", 0.182335, 13.50, description="Remove and Replace Cast Stone Window Trim"),
    ("WS3", "LF"): UnitCost("WS3", "bricklayer", 0.057579, 0.50, description="Clean Cast Stone Window Heads, Re-point and Cover all Horizontal & Vertical Joints"),
    ("WS4", "LF"): UnitCost("WS4", "bricklayer", 0.057579, 0.50, description="Clean Cast Stone Sills, Re-point and Cover all Horizontal & Vertical Joints"),
    ("WS5", "EA"): UnitCost("WS5", "bricklayer", 0.537407, 0.0, description="Refasten Loose Grille"),
    ("WS6", "SF"): UnitCost("WS6", "bricklayer", 0.057579, 0.50, description="Stonework Above Doors to be Re-caulked, Clean and Seal"),
    ("WS7", "EA"): UnitCost("WS7", "bricklayer", 0.383862, 0.0, description="Patch Holes In Face Brick"),
    ("WS8", "LF"): UnitCost("WS8", "bricklayer", 0.134352, 0.50, description="Rake Out and Re-point Brick Mortar Joints in Delineated Area"),
    ("WS9", "LF"): UnitCost("WS9", "bricklayer", 0.134352, 0.50, description="Remove & Re-caulk Expansion Joints"),
    ("WS10", "LF"): UnitCost("WS10", "bricklayer", 0.047983, 0.50, description="Re-point Horizontal Joint @ Lintels"),
    ("WS10", "SF"): UnitCost("WS10", "bricklayer", 0.047983, 0.50, description="Re-point Brick"),
    ("WS12", "SF"): UnitCost("WS12", "bricklayer", 0.095966, 10.0, description="Scrape, Wire Brush, Prime and Paint Existing Steel Lintel"),
    ("WS13", "LF"): UnitCost("WS13", "bricklayer", 0.047983, 6.54, description="Install Steel Tubing and Beam around Door Opening"),
    ("WS14", "SF"): UnitCost("WS14", "bricklayer", 0.134352, 0.0, description="Temporarily Remove Existing/Displaced Masonry Around Door"),
    ("WS15", "SF"): UnitCost("WS15", "bricklayer", 0.153545, 8.50, description="Remove Loose Brick around Lintel; Scrape, Wire Brush, Prime"),
    ("WS16", "SF"): UnitCost("WS16", "bricklayer", 0.153545, 8.50, description="Repair Cracked Brick"),
    ("WS17", "LF"): UnitCost("WS17", "bricklayer", 0.153545, 10.50, description="Refasten Loose Fascia Cover"),
    ("WS18", "SF"): UnitCost("WS18", "bricklayer", 0.119957, 0.0, description="Remove Brick"),
    ("WS19", "LF"): UnitCost("WS19", "bricklayer", 0.047983, 0.50, description="Re-point Vertical Joints"),
}

DEFAULT_MARKUP = BidMarkup()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def waste_rate_for(unit: str) -> float:
    """Lookup waste rate; warn-and-default to 0 for unknown units."""
    norm = normalize_unit(unit)
    if norm in WASTE_RATES:
        return WASTE_RATES[norm]
    logger.warning("unknown unit %r — defaulting to 0%% waste", unit)
    return 0.0


# ---------------------------------------------------------------------------
# Pricing functions
# ---------------------------------------------------------------------------


def price_scope_item(
    scope_item: ScopeItem,
    unit_cost: UnitCost,
    wage: PrevailingWage,
) -> BidLineItem:
    """Compute a priced line item for a single ScopeItem."""
    if scope_item.quantity < 0:
        raise ValueError(
            f"scope_item.quantity must be >= 0, got {scope_item.quantity!r} "
            f"for code {scope_item.code!r}"
        )
    if unit_cost.code != scope_item.code:
        logger.warning(
            "unit_cost.code=%r does not match scope_item.code=%r",
            unit_cost.code,
            scope_item.code,
        )
    if unit_cost.trade != wage.trade:
        logger.warning(
            "unit_cost.trade=%r does not match wage.trade=%r — pricing anyway",
            unit_cost.trade,
            wage.trade,
        )

    waste = waste_rate_for(scope_item.unit)
    qty_with_waste = scope_item.quantity * (1 + waste)
    unit_labor = unit_cost.hours_per_unit * wage.total
    unit_material = unit_cost.material_per_unit
    total_cost = qty_with_waste * (unit_labor + unit_material)

    logger.info(
        "priced %s: %.2f %s (×%.2f waste) → labor=$%.2f material=$%.2f total=$%.2f",
        scope_item.code,
        scope_item.quantity,
        scope_item.unit,
        1 + waste,
        qty_with_waste * unit_labor,
        qty_with_waste * unit_material,
        total_cost,
    )
    return BidLineItem(
        scope_item=scope_item,
        unit_labor=unit_labor,
        unit_material=unit_material,
        total_cost=total_cost,
    )


def price_bid(
    scope_items: Iterable[ScopeItem],
    unit_costs: Mapping[tuple[str, str], UnitCost] = DEFAULT_UNIT_COSTS,
    wages: Mapping[str, PrevailingWage] = DEFAULT_WAGES,
    markup: BidMarkup = DEFAULT_MARKUP,
) -> Bid:
    """Price a full set of scope items into a complete Bid.

    `unit_costs` is keyed by `(code, normalized_unit)` so that codes which
    have different rates per unit (e.g. WS10 LF vs WS10 SF) can coexist.
    """
    line_items: list[BidLineItem] = []
    skipped: list[str] = []
    for si in scope_items:
        key = (si.code, normalize_unit(si.unit))
        try:
            uc = unit_costs[key]
        except KeyError:
            logger.error(
                "no unit cost for %s %s — skipping line item", si.code, si.unit
            )
            skipped.append(f"{si.code}/{si.unit}")
            continue
        try:
            wage = wages[uc.trade]
        except KeyError:
            logger.error(
                "no prevailing wage for trade %r (code %r) — skipping",
                uc.trade,
                si.code,
            )
            skipped.append(f"{si.code}/{si.unit}")
            continue
        line_items.append(price_scope_item(si, uc, wage))

    if skipped:
        logger.warning("priced %d items, skipped %d: %s", len(line_items), len(skipped), skipped)

    subtotal = sum(li.total_cost for li in line_items)
    overhead = subtotal * markup.overhead
    tax = subtotal * markup.tax
    bid_bond = subtotal * markup.bid_bond
    contingencies = subtotal * markup.contingencies
    total = subtotal + overhead + tax + bid_bond + contingencies

    return Bid(
        line_items=tuple(line_items),
        subtotal=subtotal,
        overhead=overhead,
        tax=tax,
        bid_bond=bid_bond,
        contingencies=contingencies,
        total=total,
    )
